// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "parse_audio_parse_signal.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic parse_audio_parse_signal::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic parse_audio_parse_signal::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> parse_audio_parse_signal::ap_ST_st1_fsm_0 = "1";
const sc_lv<8> parse_audio_parse_signal::ap_ST_st2_fsm_1 = "10";
const sc_lv<8> parse_audio_parse_signal::ap_ST_st3_fsm_2 = "100";
const sc_lv<8> parse_audio_parse_signal::ap_ST_st4_fsm_3 = "1000";
const sc_lv<8> parse_audio_parse_signal::ap_ST_st5_fsm_4 = "10000";
const sc_lv<8> parse_audio_parse_signal::ap_ST_st6_fsm_5 = "100000";
const sc_lv<8> parse_audio_parse_signal::ap_ST_pp0_stg0_fsm_6 = "1000000";
const sc_lv<8> parse_audio_parse_signal::ap_ST_st9_fsm_7 = "10000000";
const sc_lv<32> parse_audio_parse_signal::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> parse_audio_parse_signal::ap_const_lv1_1 = "1";
const sc_lv<32> parse_audio_parse_signal::ap_const_lv32_1 = "1";
const sc_lv<1> parse_audio_parse_signal::ap_const_lv1_0 = "0";
const sc_lv<32> parse_audio_parse_signal::ap_const_lv32_2 = "10";
const sc_lv<32> parse_audio_parse_signal::ap_const_lv32_3 = "11";
const sc_lv<32> parse_audio_parse_signal::ap_const_lv32_4 = "100";
const sc_lv<32> parse_audio_parse_signal::ap_const_lv32_5 = "101";
const sc_lv<32> parse_audio_parse_signal::ap_const_lv32_6 = "110";
const sc_lv<32> parse_audio_parse_signal::ap_const_lv32_7 = "111";
const sc_lv<4> parse_audio_parse_signal::ap_const_lv4_0 = "0000";
const sc_lv<4> parse_audio_parse_signal::ap_const_lv4_C = "1100";
const sc_lv<4> parse_audio_parse_signal::ap_const_lv4_1 = "1";
const sc_lv<32> parse_audio_parse_signal::ap_const_lv32_C = "1100";

parse_audio_parse_signal::parse_audio_parse_signal(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond5_fu_145_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond5_fu_145_p2 );

    SC_METHOD(thread_ap_sig_bdd_104);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_113);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_122);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_130);
    sensitive << ( pairs_amplitude_V_full_n );
    sensitive << ( tmp_6_reg_270 );

    SC_METHOD(thread_ap_sig_bdd_153);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_166);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_bdd_27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_66);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_83);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_94);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_6);
    sensitive << ( ap_sig_bdd_122 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_27 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_66 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_83 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_94 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_104 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_bdd_113 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_7);
    sensitive << ( ap_sig_bdd_153 );

    SC_METHOD(thread_b_1_fu_207_p2);
    sensitive << ( b1_reg_136 );

    SC_METHOD(thread_duration_fu_191_p2);
    sensitive << ( tmp_4_fu_186_p2 );
    sensitive << ( smax_fu_181_p3 );

    SC_METHOD(thread_exitcond5_fu_145_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( j_reg_115 );

    SC_METHOD(thread_exitcond_fu_166_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( j1_reg_126 );

    SC_METHOD(thread_i_fu_151_p2);
    sensitive << ( j_reg_115 );

    SC_METHOD(thread_j_1_fu_213_p2);
    sensitive << ( j1_reg_126 );

    SC_METHOD(thread_j_cast1_fu_157_p1);
    sensitive << ( j_reg_115 );

    SC_METHOD(thread_locs_address0);
    sensitive << ( locs_addr_reg_232 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_locs_address1);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_2_fu_172_p1 );

    SC_METHOD(thread_locs_ce0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_locs_ce1);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_pairs_amplitude_V_din);
    sensitive << ( signal_r_q0 );
    sensitive << ( tmp_6_reg_270 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_6 );
    sensitive << ( ap_sig_bdd_130 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_pairs_amplitude_V_write);
    sensitive << ( tmp_6_reg_270 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_6 );
    sensitive << ( ap_sig_bdd_130 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_pairs_duration_V_din);
    sensitive << ( pairs_duration_V_full_n );
    sensitive << ( duration_reg_265 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_7 );

    SC_METHOD(thread_pairs_duration_V_write);
    sensitive << ( pairs_duration_V_full_n );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_7 );

    SC_METHOD(thread_signal_r_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_6 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_7_fu_202_p1 );

    SC_METHOD(thread_signal_r_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_6 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_130 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_smax_fu_181_p3);
    sensitive << ( b_reg_245 );
    sensitive << ( e_reg_253 );
    sensitive << ( tmp_3_reg_260 );

    SC_METHOD(thread_tmp_2_fu_172_p1);
    sensitive << ( j1_reg_126 );

    SC_METHOD(thread_tmp_3_fu_177_p2);
    sensitive << ( b_reg_245 );
    sensitive << ( e_reg_253 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_tmp_4_fu_186_p2);
    sensitive << ( b_reg_245 );

    SC_METHOD(thread_tmp_6_fu_197_p2);
    sensitive << ( b1_reg_136 );
    sensitive << ( e_reg_253 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_6 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_130 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_tmp_7_fu_202_p1);
    sensitive << ( b1_reg_136 );

    SC_METHOD(thread_tmp_fu_161_p1);
    sensitive << ( j_reg_115 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( pairs_duration_V_full_n );
    sensitive << ( exitcond5_fu_145_p2 );
    sensitive << ( exitcond_fu_166_p2 );
    sensitive << ( tmp_6_fu_197_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_130 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_bdd_166 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00000001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "parse_audio_parse_signal_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, signal_r_address0, "(port)signal_r_address0");
    sc_trace(mVcdFile, signal_r_ce0, "(port)signal_r_ce0");
    sc_trace(mVcdFile, signal_r_q0, "(port)signal_r_q0");
    sc_trace(mVcdFile, locs_address0, "(port)locs_address0");
    sc_trace(mVcdFile, locs_ce0, "(port)locs_ce0");
    sc_trace(mVcdFile, locs_q0, "(port)locs_q0");
    sc_trace(mVcdFile, locs_address1, "(port)locs_address1");
    sc_trace(mVcdFile, locs_ce1, "(port)locs_ce1");
    sc_trace(mVcdFile, locs_q1, "(port)locs_q1");
    sc_trace(mVcdFile, pairs_amplitude_V_din, "(port)pairs_amplitude_V_din");
    sc_trace(mVcdFile, pairs_amplitude_V_full_n, "(port)pairs_amplitude_V_full_n");
    sc_trace(mVcdFile, pairs_amplitude_V_write, "(port)pairs_amplitude_V_write");
    sc_trace(mVcdFile, pairs_duration_V_din, "(port)pairs_duration_V_din");
    sc_trace(mVcdFile, pairs_duration_V_full_n, "(port)pairs_duration_V_full_n");
    sc_trace(mVcdFile, pairs_duration_V_write, "(port)pairs_duration_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_27, "ap_sig_bdd_27");
    sc_trace(mVcdFile, b1_reg_136, "b1_reg_136");
    sc_trace(mVcdFile, i_fu_151_p2, "i_fu_151_p2");
    sc_trace(mVcdFile, i_reg_222, "i_reg_222");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_66, "ap_sig_bdd_66");
    sc_trace(mVcdFile, j_cast1_fu_157_p1, "j_cast1_fu_157_p1");
    sc_trace(mVcdFile, exitcond5_fu_145_p2, "exitcond5_fu_145_p2");
    sc_trace(mVcdFile, locs_addr_reg_232, "locs_addr_reg_232");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_83, "ap_sig_bdd_83");
    sc_trace(mVcdFile, exitcond_fu_166_p2, "exitcond_fu_166_p2");
    sc_trace(mVcdFile, b_reg_245, "b_reg_245");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_94, "ap_sig_bdd_94");
    sc_trace(mVcdFile, e_reg_253, "e_reg_253");
    sc_trace(mVcdFile, tmp_3_fu_177_p2, "tmp_3_fu_177_p2");
    sc_trace(mVcdFile, tmp_3_reg_260, "tmp_3_reg_260");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_104, "ap_sig_bdd_104");
    sc_trace(mVcdFile, duration_fu_191_p2, "duration_fu_191_p2");
    sc_trace(mVcdFile, duration_reg_265, "duration_reg_265");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_113, "ap_sig_bdd_113");
    sc_trace(mVcdFile, tmp_6_fu_197_p2, "tmp_6_fu_197_p2");
    sc_trace(mVcdFile, tmp_6_reg_270, "tmp_6_reg_270");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_6, "ap_sig_cseq_ST_pp0_stg0_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_122, "ap_sig_bdd_122");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_sig_bdd_130, "ap_sig_bdd_130");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, b_1_fu_207_p2, "b_1_fu_207_p2");
    sc_trace(mVcdFile, j_1_fu_213_p2, "j_1_fu_213_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_7, "ap_sig_cseq_ST_st9_fsm_7");
    sc_trace(mVcdFile, ap_sig_bdd_153, "ap_sig_bdd_153");
    sc_trace(mVcdFile, j_reg_115, "j_reg_115");
    sc_trace(mVcdFile, ap_sig_bdd_166, "ap_sig_bdd_166");
    sc_trace(mVcdFile, j1_reg_126, "j1_reg_126");
    sc_trace(mVcdFile, tmp_fu_161_p1, "tmp_fu_161_p1");
    sc_trace(mVcdFile, tmp_2_fu_172_p1, "tmp_2_fu_172_p1");
    sc_trace(mVcdFile, tmp_7_fu_202_p1, "tmp_7_fu_202_p1");
    sc_trace(mVcdFile, tmp_4_fu_186_p2, "tmp_4_fu_186_p2");
    sc_trace(mVcdFile, smax_fu_181_p3, "smax_fu_181_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

parse_audio_parse_signal::~parse_audio_parse_signal() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void parse_audio_parse_signal::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(exitcond5_fu_145_p2.read(), ap_const_lv1_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_6.read()) && 
             !(ap_sig_bdd_130.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_197_p2.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_6.read()) && 
             !(ap_sig_bdd_130.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_197_p2.read()))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_6.read()) && 
                     !(ap_sig_bdd_130.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
                     esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_197_p2.read())))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !(ap_sig_bdd_130.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_197_p2.read()))) {
        b1_reg_136 = b_1_fu_207_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        b1_reg_136 = b_reg_245.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_145_p2.read(), ap_const_lv1_0))) {
        j1_reg_126 = j_cast1_fu_157_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_7.read()) && 
                !esl_seteq<1,1,1>(pairs_duration_V_full_n.read(), ap_const_logic_0))) {
        j1_reg_126 = j_1_fu_213_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_166_p2.read()))) {
        j_reg_115 = i_reg_222.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !ap_sig_bdd_166.read())) {
        j_reg_115 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        b_reg_245 = locs_q0.read();
        e_reg_253 = locs_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        duration_reg_265 = duration_fu_191_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_reg_222 = i_fu_151_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(exitcond5_fu_145_p2.read(), ap_const_lv1_0))) {
        locs_addr_reg_232 =  (sc_lv<4>) (tmp_fu_161_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        tmp_3_reg_260 = tmp_3_fu_177_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_6.read()) && !(ap_sig_bdd_130.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        tmp_6_reg_270 = tmp_6_fu_197_p2.read();
    }
}

void parse_audio_parse_signal::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(exitcond5_fu_145_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void parse_audio_parse_signal::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void parse_audio_parse_signal::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(exitcond5_fu_145_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void parse_audio_parse_signal::thread_ap_sig_bdd_104() {
    ap_sig_bdd_104 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void parse_audio_parse_signal::thread_ap_sig_bdd_113() {
    ap_sig_bdd_113 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void parse_audio_parse_signal::thread_ap_sig_bdd_122() {
    ap_sig_bdd_122 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void parse_audio_parse_signal::thread_ap_sig_bdd_130() {
    ap_sig_bdd_130 = (esl_seteq<1,1,1>(pairs_amplitude_V_full_n.read(), ap_const_logic_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_reg_270.read()));
}

void parse_audio_parse_signal::thread_ap_sig_bdd_153() {
    ap_sig_bdd_153 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void parse_audio_parse_signal::thread_ap_sig_bdd_166() {
    ap_sig_bdd_166 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void parse_audio_parse_signal::thread_ap_sig_bdd_27() {
    ap_sig_bdd_27 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void parse_audio_parse_signal::thread_ap_sig_bdd_66() {
    ap_sig_bdd_66 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void parse_audio_parse_signal::thread_ap_sig_bdd_83() {
    ap_sig_bdd_83 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void parse_audio_parse_signal::thread_ap_sig_bdd_94() {
    ap_sig_bdd_94 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void parse_audio_parse_signal::thread_ap_sig_cseq_ST_pp0_stg0_fsm_6() {
    if (ap_sig_bdd_122.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_6 = ap_const_logic_0;
    }
}

void parse_audio_parse_signal::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_27.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void parse_audio_parse_signal::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_66.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void parse_audio_parse_signal::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_83.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void parse_audio_parse_signal::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_94.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void parse_audio_parse_signal::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_104.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void parse_audio_parse_signal::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_bdd_113.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void parse_audio_parse_signal::thread_ap_sig_cseq_ST_st9_fsm_7() {
    if (ap_sig_bdd_153.read()) {
        ap_sig_cseq_ST_st9_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_7 = ap_const_logic_0;
    }
}

void parse_audio_parse_signal::thread_b_1_fu_207_p2() {
    b_1_fu_207_p2 = (!b1_reg_136.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(b1_reg_136.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void parse_audio_parse_signal::thread_duration_fu_191_p2() {
    duration_fu_191_p2 = (!tmp_4_fu_186_p2.read().is_01() || !smax_fu_181_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_4_fu_186_p2.read()) + sc_biguint<32>(smax_fu_181_p3.read()));
}

void parse_audio_parse_signal::thread_exitcond5_fu_145_p2() {
    exitcond5_fu_145_p2 = (!j_reg_115.read().is_01() || !ap_const_lv4_C.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_115.read() == ap_const_lv4_C);
}

void parse_audio_parse_signal::thread_exitcond_fu_166_p2() {
    exitcond_fu_166_p2 = (!j1_reg_126.read().is_01() || !ap_const_lv32_C.is_01())? sc_lv<1>(): sc_lv<1>(j1_reg_126.read() == ap_const_lv32_C);
}

void parse_audio_parse_signal::thread_i_fu_151_p2() {
    i_fu_151_p2 = (!j_reg_115.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j_reg_115.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void parse_audio_parse_signal::thread_j_1_fu_213_p2() {
    j_1_fu_213_p2 = (!j1_reg_126.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(j1_reg_126.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void parse_audio_parse_signal::thread_j_cast1_fu_157_p1() {
    j_cast1_fu_157_p1 = esl_zext<32,4>(j_reg_115.read());
}

void parse_audio_parse_signal::thread_locs_address0() {
    locs_address0 = locs_addr_reg_232.read();
}

void parse_audio_parse_signal::thread_locs_address1() {
    locs_address1 =  (sc_lv<4>) (tmp_2_fu_172_p1.read());
}

void parse_audio_parse_signal::thread_locs_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        locs_ce0 = ap_const_logic_1;
    } else {
        locs_ce0 = ap_const_logic_0;
    }
}

void parse_audio_parse_signal::thread_locs_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        locs_ce1 = ap_const_logic_1;
    } else {
        locs_ce1 = ap_const_logic_0;
    }
}

void parse_audio_parse_signal::thread_pairs_amplitude_V_din() {
    pairs_amplitude_V_din = signal_r_q0.read();
}

void parse_audio_parse_signal::thread_pairs_amplitude_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_6.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_reg_270.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !(ap_sig_bdd_130.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        pairs_amplitude_V_write = ap_const_logic_1;
    } else {
        pairs_amplitude_V_write = ap_const_logic_0;
    }
}

void parse_audio_parse_signal::thread_pairs_duration_V_din() {
    pairs_duration_V_din = duration_reg_265.read();
}

void parse_audio_parse_signal::thread_pairs_duration_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_7.read()) && 
         !esl_seteq<1,1,1>(pairs_duration_V_full_n.read(), ap_const_logic_0))) {
        pairs_duration_V_write = ap_const_logic_1;
    } else {
        pairs_duration_V_write = ap_const_logic_0;
    }
}

void parse_audio_parse_signal::thread_signal_r_address0() {
    signal_r_address0 =  (sc_lv<14>) (tmp_7_fu_202_p1.read());
}

void parse_audio_parse_signal::thread_signal_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !(ap_sig_bdd_130.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        signal_r_ce0 = ap_const_logic_1;
    } else {
        signal_r_ce0 = ap_const_logic_0;
    }
}

void parse_audio_parse_signal::thread_smax_fu_181_p3() {
    smax_fu_181_p3 = (!tmp_3_reg_260.read()[0].is_01())? sc_lv<32>(): ((tmp_3_reg_260.read()[0].to_bool())? b_reg_245.read(): e_reg_253.read());
}

void parse_audio_parse_signal::thread_tmp_2_fu_172_p1() {
    tmp_2_fu_172_p1 = esl_sext<64,32>(j1_reg_126.read());
}

void parse_audio_parse_signal::thread_tmp_3_fu_177_p2() {
    tmp_3_fu_177_p2 = (!b_reg_245.read().is_01() || !e_reg_253.read().is_01())? sc_lv<1>(): (sc_bigint<32>(b_reg_245.read()) > sc_bigint<32>(e_reg_253.read()));
}

void parse_audio_parse_signal::thread_tmp_4_fu_186_p2() {
    tmp_4_fu_186_p2 = (!ap_const_lv32_1.is_01() || !b_reg_245.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) - sc_biguint<32>(b_reg_245.read()));
}

void parse_audio_parse_signal::thread_tmp_6_fu_197_p2() {
    tmp_6_fu_197_p2 = (!b1_reg_136.read().is_01() || !e_reg_253.read().is_01())? sc_lv<1>(): (sc_bigint<32>(b1_reg_136.read()) < sc_bigint<32>(e_reg_253.read()));
}

void parse_audio_parse_signal::thread_tmp_7_fu_202_p1() {
    tmp_7_fu_202_p1 = esl_sext<64,32>(b1_reg_136.read());
}

void parse_audio_parse_signal::thread_tmp_fu_161_p1() {
    tmp_fu_161_p1 = esl_zext<64,4>(j_reg_115.read());
}

void parse_audio_parse_signal::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_166.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond5_fu_145_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_166_p2.read())) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_6;
            break;
        case 64 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !(ap_sig_bdd_130.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_197_p2.read()))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_6;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !(ap_sig_bdd_130.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_fu_197_p2.read()))) {
                ap_NS_fsm = ap_ST_st9_fsm_7;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_6;
            }
            break;
        case 128 : 
            if (!esl_seteq<1,1,1>(pairs_duration_V_full_n.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st9_fsm_7;
            }
            break;
        default : 
            ap_NS_fsm = "XXXXXXXX";
            break;
    }
}

}

