// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="signal_hits,hls_ip_2015_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.100000,HLS_SYN_LAT=120006,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=186,HLS_SYN_LUT=367}" *)

module signal_hits (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        threshold,
        signals_V_dout,
        signals_V_empty_n,
        signals_V_read,
        hits_V_din,
        hits_V_full_n,
        hits_V_write,
        locs_V_din,
        locs_V_full_n,
        locs_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 3'b1;
parameter    ap_ST_pp0_stg0_fsm_1 = 3'b10;
parameter    ap_ST_st8_fsm_2 = 3'b100;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv17_0 = 17'b00000000000000000;
parameter    ap_const_lv23_0 = 23'b00000000000000000000000;
parameter    ap_const_lv17_1D4C0 = 17'b11101010011000000;
parameter    ap_const_lv17_1 = 17'b1;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv5_2 = 5'b10;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] threshold;
input  [31:0] signals_V_dout;
input   signals_V_empty_n;
output   signals_V_read;
output  [31:0] hits_V_din;
input   hits_V_full_n;
output   hits_V_write;
output  [31:0] locs_V_din;
input   locs_V_full_n;
output   locs_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg signals_V_read;
reg hits_V_write;
reg locs_V_write;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm = 3'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_19;
reg   [16:0] tmp_5_reg_110;
wire   [31:0] threshold_to_int_fu_126_p1;
reg   [31:0] threshold_to_int_reg_226;
wire   [0:0] notrhs3_fu_134_p2;
reg   [0:0] notrhs3_reg_231;
wire   [0:0] exitcond_fu_140_p2;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_1;
reg    ap_sig_bdd_57;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg   [0:0] tmp_10_reg_267;
reg    ap_sig_bdd_80;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
wire   [16:0] i_fu_146_p2;
wire   [31:0] tmp_12_fu_152_p1;
reg   [31:0] tmp_12_reg_245;
reg   [31:0] ap_reg_ppstg_tmp_12_reg_245_pp0_it1;
reg   [31:0] ap_reg_ppstg_tmp_12_reg_245_pp0_it2;
reg   [31:0] ap_reg_ppstg_tmp_12_reg_245_pp0_it3;
reg   [31:0] ap_reg_ppstg_tmp_12_reg_245_pp0_it4;
wire   [0:0] tmp_2_fu_171_p2;
reg   [0:0] tmp_2_reg_250;
reg   [0:0] ap_reg_ppstg_tmp_2_reg_250_pp0_it1;
reg   [0:0] ap_reg_ppstg_tmp_2_reg_250_pp0_it2;
reg   [0:0] ap_reg_ppstg_tmp_2_reg_250_pp0_it3;
reg   [31:0] tmp_11_reg_255;
reg   [31:0] ap_reg_ppstg_tmp_11_reg_255_pp0_it2;
reg   [31:0] ap_reg_ppstg_tmp_11_reg_255_pp0_it3;
reg   [31:0] ap_reg_ppstg_tmp_11_reg_255_pp0_it4;
wire   [0:0] tmp_9_fu_205_p2;
reg   [0:0] tmp_9_reg_262;
wire   [0:0] tmp_10_fu_215_p2;
wire   [22:0] tmp_fu_130_p1;
wire   [7:0] tmp_7_fu_156_p4;
wire   [0:0] notlhs2_fu_165_p2;
wire   [31:0] currAmp_to_int_fu_176_p1;
wire   [7:0] tmp_1_fu_179_p4;
wire   [22:0] tmp_4_fu_189_p1;
wire   [0:0] notrhs_fu_199_p2;
wire   [0:0] notlhs_fu_193_p2;
wire   [0:0] tmp_6_fu_211_p2;
wire   [0:0] grp_fu_121_p2;
reg    grp_fu_121_ce;
wire   [4:0] grp_fu_121_opcode;
reg    ap_sig_cseq_ST_st8_fsm_2;
reg    ap_sig_bdd_210;
reg   [2:0] ap_NS_fsm;


signal_hits_fcmp_32ns_32ns_1_4 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
signal_hits_fcmp_32ns_32ns_1_4_U0(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( signals_V_dout ),
    .din1( threshold ),
    .ce( grp_fu_121_ce ),
    .opcode( grp_fu_121_opcode ),
    .dout( grp_fu_121_p2 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(((signals_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(exitcond_fu_140_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(((signals_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (exitcond_fu_140_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(((signals_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(exitcond_fu_140_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~(((signals_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~(((signals_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~(((signals_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~(((signals_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
            ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(((signals_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (exitcond_fu_140_p2 == ap_const_lv1_0))) begin
        tmp_5_reg_110 <= i_fu_146_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        tmp_5_reg_110 <= ap_const_lv17_0;
    end
end

always @ (posedge ap_clk) begin
    if (~(((signals_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
        ap_reg_ppstg_tmp_11_reg_255_pp0_it2 <= tmp_11_reg_255;
        ap_reg_ppstg_tmp_11_reg_255_pp0_it3 <= ap_reg_ppstg_tmp_11_reg_255_pp0_it2;
        ap_reg_ppstg_tmp_11_reg_255_pp0_it4 <= ap_reg_ppstg_tmp_11_reg_255_pp0_it3;
        ap_reg_ppstg_tmp_12_reg_245_pp0_it2[16 : 0] <= ap_reg_ppstg_tmp_12_reg_245_pp0_it1[16 : 0];
        ap_reg_ppstg_tmp_12_reg_245_pp0_it3[16 : 0] <= ap_reg_ppstg_tmp_12_reg_245_pp0_it2[16 : 0];
        ap_reg_ppstg_tmp_12_reg_245_pp0_it4[16 : 0] <= ap_reg_ppstg_tmp_12_reg_245_pp0_it3[16 : 0];
        ap_reg_ppstg_tmp_2_reg_250_pp0_it2 <= ap_reg_ppstg_tmp_2_reg_250_pp0_it1;
        ap_reg_ppstg_tmp_2_reg_250_pp0_it3 <= ap_reg_ppstg_tmp_2_reg_250_pp0_it2;
        tmp_10_reg_267 <= tmp_10_fu_215_p2;
        tmp_9_reg_262 <= tmp_9_fu_205_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(((signals_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        ap_reg_ppstg_tmp_12_reg_245_pp0_it1[16 : 0] <= tmp_12_reg_245[16 : 0];
        ap_reg_ppstg_tmp_2_reg_250_pp0_it1 <= tmp_2_reg_250;
        tmp_11_reg_255 <= signals_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        notrhs3_reg_231 <= notrhs3_fu_134_p2;
        threshold_to_int_reg_226 <= threshold_to_int_fu_126_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(((signals_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & (exitcond_fu_140_p2 == ap_const_lv1_0))) begin
        tmp_12_reg_245[16 : 0] <= tmp_12_fu_152_p1[16 : 0];
        tmp_2_reg_250 <= tmp_2_fu_171_p2;
    end
end

always @ (ap_sig_cseq_ST_st8_fsm_2) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_2)) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st8_fsm_2) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_2)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_57) begin
    if (ap_sig_bdd_57) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_19) begin
    if (ap_sig_bdd_19) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_210) begin
    if (ap_sig_bdd_210) begin
        ap_sig_cseq_ST_st8_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_2 = ap_const_logic_0;
    end
end

always @ (signals_V_empty_n or ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_80 or ap_reg_ppiten_pp0_it5) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(((signals_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        grp_fu_121_ce = ap_const_logic_1;
    end else begin
        grp_fu_121_ce = ap_const_logic_0;
    end
end

always @ (signals_V_empty_n or ap_reg_ppiten_pp0_it1 or tmp_10_reg_267 or ap_sig_bdd_80 or ap_reg_ppiten_pp0_it5) begin
    if ((~(tmp_10_reg_267 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~(((signals_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        hits_V_write = ap_const_logic_1;
    end else begin
        hits_V_write = ap_const_logic_0;
    end
end

always @ (signals_V_empty_n or ap_reg_ppiten_pp0_it1 or tmp_10_reg_267 or ap_sig_bdd_80 or ap_reg_ppiten_pp0_it5) begin
    if ((~(tmp_10_reg_267 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~(((signals_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        locs_V_write = ap_const_logic_1;
    end else begin
        locs_V_write = ap_const_logic_0;
    end
end

always @ (signals_V_empty_n or ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_80 or ap_reg_ppiten_pp0_it5) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(((signals_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))))) begin
        signals_V_read = ap_const_logic_1;
    end else begin
        signals_V_read = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or signals_V_empty_n or exitcond_fu_140_p2 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_80 or ap_reg_ppiten_pp0_it5) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_pp0_stg0_fsm_1 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~(((signals_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(((signals_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(exitcond_fu_140_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~(((signals_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(((signals_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5))) & ~(exitcond_fu_140_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st8_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end
        end
        ap_ST_st8_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end



always @ (ap_CS_fsm) begin
    ap_sig_bdd_19 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_210 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_57 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (hits_V_full_n or locs_V_full_n or tmp_10_reg_267) begin
    ap_sig_bdd_80 = (((hits_V_full_n == ap_const_logic_0) & ~(tmp_10_reg_267 == ap_const_lv1_0)) | (~(tmp_10_reg_267 == ap_const_lv1_0) & (locs_V_full_n == ap_const_logic_0)));
end

assign currAmp_to_int_fu_176_p1 = ap_reg_ppstg_tmp_11_reg_255_pp0_it2;

assign exitcond_fu_140_p2 = (tmp_5_reg_110 == ap_const_lv17_1D4C0? 1'b1: 1'b0);

assign grp_fu_121_opcode = ap_const_lv5_2;

assign hits_V_din = ap_reg_ppstg_tmp_11_reg_255_pp0_it4;

assign i_fu_146_p2 = (tmp_5_reg_110 + ap_const_lv17_1);

assign locs_V_din = ap_reg_ppstg_tmp_12_reg_245_pp0_it4;

assign notlhs2_fu_165_p2 = (tmp_7_fu_156_p4 != ap_const_lv8_FF? 1'b1: 1'b0);

assign notlhs_fu_193_p2 = (tmp_1_fu_179_p4 != ap_const_lv8_FF? 1'b1: 1'b0);

assign notrhs3_fu_134_p2 = (tmp_fu_130_p1 == ap_const_lv23_0? 1'b1: 1'b0);

assign notrhs_fu_199_p2 = (tmp_4_fu_189_p1 == ap_const_lv23_0? 1'b1: 1'b0);

assign threshold_to_int_fu_126_p1 = threshold;

assign tmp_10_fu_215_p2 = (tmp_6_fu_211_p2 & grp_fu_121_p2);

assign tmp_12_fu_152_p1 = tmp_5_reg_110;

assign tmp_1_fu_179_p4 = {{currAmp_to_int_fu_176_p1[ap_const_lv32_1E : ap_const_lv32_17]}};

assign tmp_2_fu_171_p2 = (notrhs3_reg_231 | notlhs2_fu_165_p2);

assign tmp_4_fu_189_p1 = currAmp_to_int_fu_176_p1[22:0];

assign tmp_6_fu_211_p2 = (tmp_9_reg_262 & ap_reg_ppstg_tmp_2_reg_250_pp0_it3);

assign tmp_7_fu_156_p4 = {{threshold_to_int_reg_226[ap_const_lv32_1E : ap_const_lv32_17]}};

assign tmp_9_fu_205_p2 = (notrhs_fu_199_p2 | notlhs_fu_193_p2);

assign tmp_fu_130_p1 = threshold_to_int_fu_126_p1[22:0];
always @ (posedge ap_clk) begin
    tmp_12_reg_245[31:17] <= 15'b000000000000000;
    ap_reg_ppstg_tmp_12_reg_245_pp0_it1[31:17] <= 15'b000000000000000;
    ap_reg_ppstg_tmp_12_reg_245_pp0_it2[31:17] <= 15'b000000000000000;
    ap_reg_ppstg_tmp_12_reg_245_pp0_it3[31:17] <= 15'b000000000000000;
    ap_reg_ppstg_tmp_12_reg_245_pp0_it4[31:17] <= 15'b000000000000000;
end



endmodule //signal_hits

