// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// ==============================================================

extern void peaks (
hls::stream<float >& samples,
hls::stream<float >& amplitude,
hls::stream<int >& locations);
