// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "amplitude_V"
#define AUTOTB_TVIN_amplitude_V  "../tv/cdatafile/c.running_threshold.autotvin_amplitude_V.dat"
#define WRAPC_STREAM_SIZE_IN_amplitude_V  "../tv/stream_size/stream_size_in_amplitude_V.dat"
#define WRAPC_STREAM_INGRESS_STATUS_amplitude_V  "../tv/stream_size/stream_ingress_status_amplitude_V.dat"
// wrapc file define: "threshold_V"
#define AUTOTB_TVOUT_threshold_V  "../tv/cdatafile/c.running_threshold.autotvout_threshold_V.dat"
#define AUTOTB_TVIN_threshold_V  "../tv/cdatafile/c.running_threshold.autotvin_threshold_V.dat"
#define WRAPC_STREAM_SIZE_OUT_threshold_V  "../tv/stream_size/stream_size_out_threshold_V.dat"
#define WRAPC_STREAM_EGRESS_STATUS_threshold_V  "../tv/stream_size/stream_egress_status_threshold_V.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "threshold_V"
#define AUTOTB_TVOUT_PC_threshold_V  "../tv/rtldatafile/rtl.running_threshold.autotvout_threshold_V.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			amplitude_V_depth = 0;
			threshold_V_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{amplitude_V " << amplitude_V_depth << "}\n";
			total_list << "{threshold_V " << threshold_V_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int amplitude_V_depth;
		int threshold_V_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};


#define running_threshold AESL_ORIG_DUT_running_threshold
extern void running_threshold (
hls::stream<float >& amplitude,
hls::stream<float >& threshold);
#undef running_threshold

void running_threshold (
hls::stream<float >& amplitude,
hls::stream<float >& threshold)
{
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;

		// pop stream input: "amplitude"
		aesl_fh.read(WRAPC_STREAM_SIZE_IN_amplitude_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_IN_amplitude_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_IN_amplitude_V, AESL_token); // pop_size
			int aesl_tmp_1 = atoi(AESL_token.c_str());
			for (int i = 0; i < aesl_tmp_1; i++)
			{
				amplitude.read();
			}
			aesl_fh.read(WRAPC_STREAM_SIZE_IN_amplitude_V, AESL_token); // [[/transaction]]
		}

		// define output stream variables: "threshold"
		std::vector<float > aesl_tmp_3;
		int aesl_tmp_4;
		int aesl_tmp_5 = 0;

		// read output stream size: "threshold"
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_threshold_V, AESL_token); // [[transaction]]
		aesl_fh.read(WRAPC_STREAM_SIZE_OUT_threshold_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_threshold_V, AESL_token); // pop_size
			aesl_tmp_4 = atoi(AESL_token.c_str());
			aesl_fh.read(WRAPC_STREAM_SIZE_OUT_threshold_V, AESL_token); // [[/transaction]]
		}

		// output port post check: "threshold_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_threshold_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_threshold_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_threshold_V, AESL_token); // data

			std::vector<sc_bv<32> > threshold_V_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'threshold_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'threshold_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					threshold_V_pc_buffer.push_back(AESL_token.c_str());
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_threshold_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_threshold_V))
				{
					exit(1);
				}
			}

			// correct the buffer size the current transaction
			if (i != aesl_tmp_4)
			{
				aesl_tmp_4 = i;
			}

			if (aesl_tmp_4 > 0 && aesl_tmp_3.size() < aesl_tmp_4)
			{
				int aesl_tmp_3_size = aesl_tmp_3.size();

				for (int tmp_aesl_tmp_3 = 0; tmp_aesl_tmp_3 < aesl_tmp_4 - aesl_tmp_3_size; tmp_aesl_tmp_3++)
				{
					float tmp;
					aesl_tmp_3.push_back(tmp);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: threshold_V
				{
					// bitslice(31, 0)
					// {
						// celement: threshold.V(31, 0)
						// {
							sc_lv<32>* threshold_V_lv0_0_0_1 = new sc_lv<32>[aesl_tmp_4 - aesl_tmp_5];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: threshold.V(31, 0)
						{
							// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
							for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
							{
								if (&(aesl_tmp_3[0]) != NULL) // check the null address if the c port is array or others
								{
									threshold_V_lv0_0_0_1[hls_map_index++].range(31, 0) = sc_bv<32>(threshold_V_pc_buffer[hls_map_index].range(31, 0));
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: threshold.V(31, 0)
						{
							// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
							for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : aesl_tmp_3[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : aesl_tmp_3[0]
								// output_left_conversion : *(int*)&aesl_tmp_3[i_0]
								// output_type_conversion : (threshold_V_lv0_0_0_1[hls_map_index++]).to_uint64()
								if (&(aesl_tmp_3[0]) != NULL) // check the null address if the c port is array or others
								{
									*(int*)&aesl_tmp_3[i_0] = (threshold_V_lv0_0_0_1[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}
		}

		// push back output stream: "threshold"
		for (int i = 0; i < aesl_tmp_4; i++)
		{
			threshold.write(aesl_tmp_3[i]);
		}

		AESL_transaction_pc++;
	}
	else
	{
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "amplitude_V"
		char* tvin_amplitude_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_amplitude_V);
		char* wrapc_stream_size_in_amplitude_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_IN_amplitude_V);
		char* wrapc_stream_ingress_status_amplitude_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_INGRESS_STATUS_amplitude_V);

		// "threshold_V"
		char* tvin_threshold_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_threshold_V);
		char* tvout_threshold_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_threshold_V);
		char* wrapc_stream_size_out_threshold_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_SIZE_OUT_threshold_V);
		char* wrapc_stream_egress_status_threshold_V = new char[50];
		aesl_fh.touch(WRAPC_STREAM_EGRESS_STATUS_threshold_V);

		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// dump stream tvin: "amplitude"
		std::vector<float > aesl_tmp_0;
		int aesl_tmp_1 = 0;
		while (!amplitude.empty())
		{
			aesl_tmp_0.push_back(amplitude.read());
			aesl_tmp_1++;
		}

		// dump stream tvin: "threshold"
		std::vector<float > aesl_tmp_3;
		int aesl_tmp_4 = 0;
		while (!threshold.empty())
		{
			aesl_tmp_3.push_back(threshold.read());
			aesl_tmp_4++;
		}

		// push back input stream: "amplitude"
		for (int i = 0; i < aesl_tmp_1; i++)
		{
			amplitude.write(aesl_tmp_0[i]);
		}

		// push back input stream: "threshold"
		for (int i = 0; i < aesl_tmp_4; i++)
		{
			threshold.write(aesl_tmp_3[i]);
		}

// [call_c_dut] ---------->

		AESL_ORIG_DUT_running_threshold(amplitude, threshold);

		// record input size to tv3: "amplitude"
		int aesl_tmp_2 = amplitude.size();

		// pop output stream: "threshold"
		int aesl_tmp_5 = aesl_tmp_4;
		aesl_tmp_4 = 0;
     aesl_tmp_3.clear();
		while (!threshold.empty())
		{
			aesl_tmp_3.push_back(threshold.read());
			aesl_tmp_4++;
		}

		// [[transaction]]
		sprintf(tvin_amplitude_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_amplitude_V, tvin_amplitude_V);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_amplitude_V, tvin_amplitude_V);

		sc_bv<32>* amplitude_V_tvin_wrapc_buffer = new sc_bv<32>[aesl_tmp_1 - aesl_tmp_2];

		// RTL Name: amplitude_V
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: amplitude.V(31, 0)
				{
					// carray: (0) => (aesl_tmp_1 - aesl_tmp_2 - 1) @ (1)
					for (int i_0 = 0; i_0 <= aesl_tmp_1 - aesl_tmp_2 - 1; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : aesl_tmp_0[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : aesl_tmp_0[0]
						// regulate_c_name       : amplitude_V
						// input_type_conversion : *(int*)&aesl_tmp_0[i_0]
						if (&(aesl_tmp_0[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> amplitude_V_tmp_mem;
							amplitude_V_tmp_mem = *(int*)&aesl_tmp_0[i_0];
							amplitude_V_tvin_wrapc_buffer[hls_map_index++].range(31, 0) = amplitude_V_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2; i++)
		{
			sprintf(tvin_amplitude_V, "%s\n", (amplitude_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_amplitude_V, tvin_amplitude_V);
		}

		// dump stream ingress status to file
		sc_int<32> stream_ingress_size_amplitude_V = aesl_tmp_1;
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_amplitude_V, stream_ingress_size_amplitude_V.to_string().c_str());
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_amplitude_V, "\n");

		for (int i = 0; i < aesl_tmp_1 - aesl_tmp_2; i++)
		{
			stream_ingress_size_amplitude_V--;
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_amplitude_V, stream_ingress_size_amplitude_V.to_string().c_str());
			aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_amplitude_V, "\n");
		}

		tcl_file.set_num(aesl_tmp_1 - aesl_tmp_2, &tcl_file.amplitude_V_depth);
		sprintf(tvin_amplitude_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_amplitude_V, tvin_amplitude_V);
		aesl_fh.write(WRAPC_STREAM_INGRESS_STATUS_amplitude_V, tvin_amplitude_V);

		// release memory allocation
		delete [] amplitude_V_tvin_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_in_amplitude_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_amplitude_V, wrapc_stream_size_in_amplitude_V);
		sprintf(wrapc_stream_size_in_amplitude_V, "%d\n", aesl_tmp_1 - aesl_tmp_2);
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_amplitude_V, wrapc_stream_size_in_amplitude_V);
		sprintf(wrapc_stream_size_in_amplitude_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_IN_amplitude_V, wrapc_stream_size_in_amplitude_V);

		// [[transaction]]
		sprintf(tvout_threshold_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_threshold_V, tvout_threshold_V);

		sc_bv<32>* threshold_V_tvout_wrapc_buffer = new sc_bv<32>[aesl_tmp_4 - aesl_tmp_5];

		// RTL Name: threshold_V
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: threshold.V(31, 0)
				{
					// carray: (aesl_tmp_5) => (aesl_tmp_4 - 1) @ (1)
					for (int i_0 = aesl_tmp_5; i_0 <= aesl_tmp_4 - 1; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : aesl_tmp_3[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : aesl_tmp_3[0]
						// regulate_c_name       : threshold_V
						// input_type_conversion : *(int*)&aesl_tmp_3[i_0]
						if (&(aesl_tmp_3[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> threshold_V_tmp_mem;
							threshold_V_tmp_mem = *(int*)&aesl_tmp_3[i_0];
							threshold_V_tvout_wrapc_buffer[hls_map_index++].range(31, 0) = threshold_V_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < aesl_tmp_4 - aesl_tmp_5; i++)
		{
			sprintf(tvout_threshold_V, "%s\n", (threshold_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_threshold_V, tvout_threshold_V);
		}

		tcl_file.set_num(aesl_tmp_4 - aesl_tmp_5, &tcl_file.threshold_V_depth);
		sprintf(tvout_threshold_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_threshold_V, tvout_threshold_V);

		// release memory allocation
		delete [] threshold_V_tvout_wrapc_buffer;

		// dump stream size
		sprintf(wrapc_stream_size_out_threshold_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_threshold_V, wrapc_stream_size_out_threshold_V);
		sprintf(wrapc_stream_size_out_threshold_V, "%d\n", aesl_tmp_4 - aesl_tmp_5);
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_threshold_V, wrapc_stream_size_out_threshold_V);
		sprintf(wrapc_stream_size_out_threshold_V, "[[/transaction]] \n");
		aesl_fh.write(WRAPC_STREAM_SIZE_OUT_threshold_V, wrapc_stream_size_out_threshold_V);

		// push back output stream: "threshold"
		for (int i = 0; i < aesl_tmp_4; i++)
		{
			threshold.write(aesl_tmp_3[i]);
		}

		// release memory allocation: "amplitude_V"
		delete [] tvin_amplitude_V;
		delete [] wrapc_stream_size_in_amplitude_V;
		// release memory allocation: "threshold_V"
		delete [] tvout_threshold_V;
		delete [] tvin_threshold_V;
		delete [] wrapc_stream_size_out_threshold_V;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

