#pragma line 1 "duplicate.cpp" ::: -10
#pragma line 1 "duplicate.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 153 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "C:/Xilinx/SDx/2016.4/Vivado_HLS/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 2
#pragma line 99 "C:/Xilinx/SDx/2016.4/Vivado_HLS/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 9
#pragma line 361 "C:/Xilinx/SDx/2016.4/Vivado_HLS/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 144
#pragma line 375 "C:/Xilinx/SDx/2016.4/Vivado_HLS/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 147
#pragma line 8 "<command line>" 2 ::: 149
#pragma line 1 "<built-in>" 2 ::: 150
#pragma line 1 "duplicate.cpp" 2 ::: 151
#pragma line 1 "./duplicate.h" 1 ::: 152
#pragma line 1 "./definitions.h" 1 ::: 157
#pragma line 1 "C:/Xilinx/SDx/2016.4/Vivado_HLS/common/technology/autopilot\\hls_stream.h" 1 ::: 161
#pragma line 1 "C:/Xilinx/SDx/2016.4/Vivado_HLS/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 182
#pragma line 21 "C:/Xilinx/SDx/2016.4/Vivado_HLS/common/technology/autopilot\\hls_stream.h" 2 ::: 271
#pragma line 5 "./definitions.h" 2 ::: 377
#pragma line 6 "./duplicate.h" 2 ::: 384
#pragma line 2 "duplicate.cpp" 2 ::: 388
