#pragma line 1 "duplicate.cpp" ::: 0
#pragma line 1 "duplicate.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 153 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "C:/Xilinx/SDx/2016.4/Vivado_HLS/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 12
#pragma line 99 "C:/Xilinx/SDx/2016.4/Vivado_HLS/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 19
#pragma line 361 "C:/Xilinx/SDx/2016.4/Vivado_HLS/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 154
#pragma line 375 "C:/Xilinx/SDx/2016.4/Vivado_HLS/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 157
#pragma line 8 "<command line>" 2 ::: 159
#pragma line 1 "<built-in>" 2 ::: 160
#pragma line 1 "duplicate.cpp" 2 ::: 161
#pragma line 1 "./duplicate.h" 1 ::: 162
#pragma line 1 "./definitions.h" 1 ::: 167
#pragma line 1 "C:/Xilinx/SDx/2016.4/Vivado_HLS/common/technology/autopilot\\hls_stream.h" 1 ::: 171
#pragma line 1 "C:/Xilinx/SDx/2016.4/Vivado_HLS/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 192
#pragma line 21 "C:/Xilinx/SDx/2016.4/Vivado_HLS/common/technology/autopilot\\hls_stream.h" 2 ::: 281
#pragma line 5 "./definitions.h" 2 ::: 387
#pragma line 6 "./duplicate.h" 2 ::: 394
#pragma line 2 "duplicate.cpp" 2 ::: 398
