// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

 `timescale 1ns/1ps


`define AUTOTB_DUT      running_threshold
`define AUTOTB_DUT_INST AESL_inst_running_threshold
`define AUTOTB_TOP      apatb_running_threshold_top
`define AUTOTB_LAT_RESULT_FILE "running_threshold.result.lat.rb"
`define AUTOTB_PER_RESULT_TRANS_FILE "running_threshold.performance.result.transaction.xml"
`define AUTOTB_TOP_INST AESL_inst_apatb_running_threshold_top
`define AUTOTB_MAX_ALLOW_LATENCY  15000000
`define AUTOTB_TRANSACTION_NUM  1
`define AUTOTB_CLOCK_PERIOD_DIV2 2.50
`define LENGTH_amplitude_V 120000
`define LENGTH_threshold_V 1

`define	AESL_FIFO_amplitude_V AESL_autofifo_amplitude_V
`define	AESL_FIFO_INST_amplitude_V AESL_autofifo_inst_amplitude_V
`define	AESL_FIFO_threshold_V AESL_autofifo_threshold_V
`define	AESL_FIFO_INST_threshold_V AESL_autofifo_inst_threshold_V
`define AUTOTB_TVIN_amplitude_V  "../tv/cdatafile/c.running_threshold.autotvin_amplitude_V.dat"
`define AUTOTB_TVIN_threshold_V  "../tv/cdatafile/c.running_threshold.autotvin_threshold_V.dat"
`define AUTOTB_TVIN_amplitude_V_out_wrapc  "../tv/rtldatafile/rtl.running_threshold.autotvin_amplitude_V.dat"
`define AUTOTB_TVIN_threshold_V_out_wrapc  "../tv/rtldatafile/rtl.running_threshold.autotvin_threshold_V.dat"
`define AUTOTB_TVOUT_threshold_V  "../tv/cdatafile/c.running_threshold.autotvout_threshold_V.dat"
`define AUTOTB_TVOUT_threshold_V_out_wrapc  "../tv/rtldatafile/rtl.running_threshold.autotvout_threshold_V.dat"

module `AUTOTB_TOP;

task read_token;
    input integer fp;
    output reg [175 : 0] token;
    reg [7:0] c;
    reg intoken;
    reg done;
    begin
        token = "";
        intoken = 0;
        done = 0;
        while (!done) begin
            c = $fgetc(fp);
            if (c == 8'hff) begin   // EOF
                done = 1;
            end
            else if (c == " " || c == "\011" || c == "\012" || c == "\015") begin   // blank
                if (intoken) begin
                    done = 1;
                end
            end
            else begin              // valid character
                intoken = 1;
                token = (token << 8) | c;
            end
        end
    end
endtask

reg AESL_clock;
reg rst;
reg start;
reg ce;
reg continue;
wire AESL_start;
wire AESL_reset;
wire AESL_ce;
wire AESL_ready;
wire AESL_idle;
wire AESL_continue;
wire AESL_done;
reg AESL_done_delay = 0;
reg AESL_done_delay2 = 0;
reg AESL_ready_delay = 0;
wire ready;
wire ready_wire;
reg [31 : 0] AESL_mLatCnterIn [0 : `AUTOTB_TRANSACTION_NUM + 1];
reg [31 : 0] AESL_mLatCnterIn_addr;
reg [31 : 0] AESL_mLatCnterOut [0 : `AUTOTB_TRANSACTION_NUM + 1];
reg [31 : 0] AESL_mLatCnterOut_addr ;
reg [31 : 0] AESL_clk_counter ;
reg [22 - 1 : 0] AESL_clk_ready[0 : `AUTOTB_TRANSACTION_NUM + 1];
reg [22 - 1 : 0] AESL_clk_done[0 : `AUTOTB_TRANSACTION_NUM + 1];

reg reported_stuck = 0;
reg reported_stuck_cnt = 0;
wire ap_start;
wire ap_done;
wire ap_idle;
wire ap_ready;
wire [31 : 0] amplitude_V_dout;
wire  amplitude_V_empty_n;
wire  amplitude_V_read;
wire [31 : 0] threshold_V_din;
wire  threshold_V_full_n;
wire  threshold_V_write;
integer done_cnt = 0;
integer AESL_ready_cnt = 0;
integer ready_cnt = 0;
reg ready_initial;
reg ready_initial_n;
reg ready_last_n;
reg ready_delay_last_n;
reg done_delay_last_n;
reg interface_done = 0;

`AUTOTB_DUT `AUTOTB_DUT_INST(
	.ap_clk(ap_clk),
	.ap_rst(ap_rst),
	.ap_start(ap_start),
	.ap_done(ap_done),
	.ap_idle(ap_idle),
	.ap_ready(ap_ready),
	.amplitude_V_dout(amplitude_V_dout),
	.amplitude_V_empty_n(amplitude_V_empty_n),
	.amplitude_V_read(amplitude_V_read),
	.threshold_V_din(threshold_V_din),
	.threshold_V_full_n(threshold_V_full_n),
	.threshold_V_write(threshold_V_write));

// Assignment for control signal
assign ap_clk = AESL_clock;
assign ap_rst = AESL_reset;
assign ap_rst_n = ~AESL_reset;
assign AESL_reset = rst;
assign ap_start = AESL_start;
assign AESL_start = start;
assign AESL_done = ap_done;
assign AESL_idle = ap_idle;
assign AESL_ready = ap_ready;
assign AESL_ce = ce;
assign AESL_continue = continue;
	always @(posedge AESL_clock) begin
		if (AESL_reset) begin
		end else begin
			if (AESL_done !== 1 && AESL_done !== 0) begin
				$display("ERROR: Control signal AESL_done is invalid!");
				$finish;
			end
		end
	end
	always @(posedge AESL_clock) begin
		if (AESL_reset) begin
		end else begin
			if (AESL_ready !== 1 && AESL_ready !== 0) begin
				$display("ERROR: Control signal AESL_ready is invalid!");
				$finish;
			end
		end
	end
// Fifo Instantiation amplitude_V

wire fifoamplitude_V_rd;
wire [31 : 0] fifoamplitude_V_dout;
wire fifoamplitude_V_empty_n;
wire fifoamplitude_V_ready;
wire fifoamplitude_V_done;
reg [31:0] ap_c_n_tvin_trans_num_amplitude_V;
reg amplitude_V_ready_reg;

`AESL_FIFO_amplitude_V `AESL_FIFO_INST_amplitude_V(
    .clk          (AESL_clock),
    .reset        (AESL_reset),
    .if_write     (),
    .if_din       (),
    .if_full_n    (),
    .if_read      (fifoamplitude_V_rd),
    .if_dout      (fifoamplitude_V_dout),
    .if_empty_n   (fifoamplitude_V_empty_n),
    .ready        (fifoamplitude_V_ready),
    .done         (fifoamplitude_V_done)
);

// Assignment between dut and fifoamplitude_V

// Assign input of fifoamplitude_V
assign      fifoamplitude_V_rd        =   amplitude_V_read & amplitude_V_empty_n;
assign    fifoamplitude_V_ready   =   amplitude_V_ready_reg | ready_initial;
assign    fifoamplitude_V_done    =   0;
// Assign input of dut
assign      amplitude_V_dout       =   fifoamplitude_V_dout;
reg   reg_fifoamplitude_V_empty_n;
initial begin : gen_reg_fifoamplitude_V_empty_n_process
	integer rand;
	reg_fifoamplitude_V_empty_n = fifoamplitude_V_empty_n;
	while (1) begin
		@ (fifoamplitude_V_empty_n);
		reg_fifoamplitude_V_empty_n = fifoamplitude_V_empty_n;
	end
end

assign      amplitude_V_empty_n    =   reg_fifoamplitude_V_empty_n;


//------------------------Fifothreshold_V Instantiation--------------

// The input and output of fifothreshold_V
wire  fifothreshold_V_wr;
wire  [31 : 0] fifothreshold_V_din;
wire  fifothreshold_V_full_n;
wire  fifothreshold_V_ready;
wire  fifothreshold_V_done;

`AESL_FIFO_threshold_V `AESL_FIFO_INST_threshold_V(
    .clk          (AESL_clock),
    .reset        (AESL_reset),
    .if_write     (fifothreshold_V_wr),
    .if_din       (fifothreshold_V_din),
    .if_full_n    (fifothreshold_V_full_n),
    .if_read      (),
    .if_dout      (),
    .if_empty_n   (),
    .ready        (fifothreshold_V_ready),
    .done         (fifothreshold_V_done)
);

// Assignment between dut and fifothreshold_V

// Assign input of fifothreshold_V
assign      fifothreshold_V_wr        =   threshold_V_write & threshold_V_full_n;
assign      fifothreshold_V_din        =   threshold_V_din;
assign    fifothreshold_V_ready   =  0;   //ready_initial | AESL_done_delay;
assign    fifothreshold_V_done    =   AESL_done_delay;
// Assign input of dut
reg   reg_fifothreshold_V_full_n;
initial begin : gen_reg_fifothreshold_V_full_n_process
	integer rand;
	reg_fifothreshold_V_full_n = fifothreshold_V_full_n;
	while (1) begin
		@ (fifothreshold_V_full_n);
		reg_fifothreshold_V_full_n = fifothreshold_V_full_n;
	end
end

assign      threshold_V_full_n    =   reg_fifothreshold_V_full_n;


initial begin : generate_AESL_ready_cnt_proc
    AESL_ready_cnt = 0;
    wait(AESL_reset === 0);
    while(AESL_ready_cnt != `AUTOTB_TRANSACTION_NUM) begin
        while(AESL_ready !== 1) begin
            @(posedge AESL_clock);
            # 0.4;
        end
        @(negedge AESL_clock);
        AESL_ready_cnt = AESL_ready_cnt + 1;
        @(posedge AESL_clock);
        # 0.4;
    end
end

	event next_trigger_ready_cnt;
	
	initial begin : gen_ready_cnt
		ready_cnt = 0;
		wait (AESL_reset === 0);
		forever begin
			@ (posedge AESL_clock);
			if (ready == 1) begin
				if (ready_cnt < `AUTOTB_TRANSACTION_NUM) begin
					ready_cnt = ready_cnt + 1;
				end
			end
			-> next_trigger_ready_cnt;
		end
	end
	
	wire all_finish = (done_cnt == `AUTOTB_TRANSACTION_NUM);
	
	// done_cnt
	always @ (posedge AESL_clock) begin
		if (AESL_reset) begin
			done_cnt <= 0;
		end else begin
			if (AESL_done == 1) begin
				if (done_cnt < `AUTOTB_TRANSACTION_NUM) begin
					done_cnt <= done_cnt + 1;
				end
			end
		end
	end
	
	initial begin : finish_simulation
		wait (all_finish == 1);
		// last transaction is saved at negedge right after last done
		@ (posedge AESL_clock);
		@ (posedge AESL_clock);
		@ (posedge AESL_clock);
		@ (posedge AESL_clock);
		$finish;
	end
	
initial begin
    AESL_clock = 0;
    forever #`AUTOTB_CLOCK_PERIOD_DIV2 AESL_clock = ~AESL_clock;
end


reg end_amplitude_V;
reg [31:0] size_amplitude_V;
reg end_threshold_V;
reg [31:0] size_threshold_V;

initial begin : initial_process
    integer rand;
    rst = 1;
    # 100;
	  repeat(3) @(posedge AESL_clock);
    rst = 0;
end

initial begin : start_process
	integer rand;
	start = 0;
	ce = 1;
	wait (AESL_reset === 0);
	@ (posedge AESL_clock);
	start = 1;
	while (ready_cnt < `AUTOTB_TRANSACTION_NUM + 1) begin
		@ (posedge AESL_clock);
	end
	start = 0;
end

always @(AESL_done)
begin
    continue = AESL_done;
end

initial begin : ready_initial_process
    ready_initial = 0;
    wait (AESL_start === 1);
    ready_initial = 1;
    @(posedge AESL_clock);
    ready_initial = 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset)
      AESL_ready_delay = 0;
  else
      AESL_ready_delay = AESL_ready;
end
initial begin : ready_last_n_process
  ready_last_n = 1;
  wait(ready_cnt == `AUTOTB_TRANSACTION_NUM)
  @(posedge AESL_clock);
  ready_last_n <= 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset)
      ready_delay_last_n = 0;
  else
      ready_delay_last_n <= ready_last_n;
end
assign ready = (ready_initial | AESL_ready_delay);
assign ready_wire = ready_initial | AESL_ready_delay;
initial begin : done_delay_last_n_process
  done_delay_last_n = 1;
  while(done_cnt < `AUTOTB_TRANSACTION_NUM)
      @(posedge AESL_clock);
  # 0.1;
  done_delay_last_n = 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset)
  begin
      AESL_done_delay <= 0;
      AESL_done_delay2 <= 0;
  end
  else begin
      AESL_done_delay <= AESL_done & done_delay_last_n;
      AESL_done_delay2 <= AESL_done_delay;
  end
end
always @(posedge AESL_clock)
begin
    if(AESL_reset)
      interface_done = 0;
  else begin
      # 0.01;
      if(ready === 1 && ready_cnt > 0 && ready_cnt < `AUTOTB_TRANSACTION_NUM)
          interface_done = 1;
      else if(AESL_done_delay === 1 && done_cnt == `AUTOTB_TRANSACTION_NUM)
          interface_done = 1;
      else
          interface_done = 0;
  end
end
initial begin : proc_gen_amplitude_V_internal_ready
    integer internal_trans_num;
    wait(AESL_reset === 0);
    wait (ready_initial === 1);
    amplitude_V_ready_reg <= 0;
    @(posedge AESL_clock);
    internal_trans_num = 1;
    while(internal_trans_num != `AUTOTB_TRANSACTION_NUM + 1) begin
        if (ap_c_n_tvin_trans_num_amplitude_V > internal_trans_num) begin
            amplitude_V_ready_reg <= 1;
            @(posedge AESL_clock);
            amplitude_V_ready_reg <= 0;
            internal_trans_num = internal_trans_num + 1;
        end
        else begin
            @(posedge AESL_clock);
        end
    end
    amplitude_V_ready_reg <= 0;
end
	`define STREAM_SIZE_IN_amplitude_V "../tv/stream_size/stream_size_in_amplitude_V.dat"
	
	initial begin : gen_ap_c_n_tvin_trans_num_amplitude_V
		integer fp_amplitude_V;
		reg [127:0] token_amplitude_V;
		integer ret;
		
		ap_c_n_tvin_trans_num_amplitude_V = 0;
		end_amplitude_V = 0;
		wait (AESL_reset === 0);
		
		fp_amplitude_V = $fopen(`STREAM_SIZE_IN_amplitude_V, "r");
		if(fp_amplitude_V == 0) begin
			$display("Failed to open file \"%s\"!", `STREAM_SIZE_IN_amplitude_V);
			$finish;
		end
		read_token(fp_amplitude_V, token_amplitude_V); // should be [[[runtime]]]
		if (token_amplitude_V != "[[[runtime]]]") begin
			$display("ERROR: token_amplitude_V != \"[[[runtime]]]\"");
			$finish;
		end
		size_amplitude_V = 0;
		while (size_amplitude_V == 0 && end_amplitude_V == 0) begin
			ap_c_n_tvin_trans_num_amplitude_V = ap_c_n_tvin_trans_num_amplitude_V + 1;
			read_token(fp_amplitude_V, token_amplitude_V); // should be [[transaction]] or [[[/runtime]]]
			if (token_amplitude_V == "[[transaction]]") begin
				read_token(fp_amplitude_V, token_amplitude_V); // should be transaction number
				read_token(fp_amplitude_V, token_amplitude_V); // should be size for hls::stream
				ret = $sscanf(token_amplitude_V, "%d", size_amplitude_V);
				read_token(fp_amplitude_V, token_amplitude_V); // should be [[/transaction]]
			end else if (token_amplitude_V == "[[[/runtime]]]") begin
				$fclose(fp_amplitude_V);
				end_amplitude_V = 1;
			end else begin
				$display("ERROR: unknown token_amplitude_V");
				$finish;
			end
		end
		forever begin
			@ (posedge AESL_clock);
			if (end_amplitude_V == 0) begin
				if (amplitude_V_read == 1) begin
					if (size_amplitude_V > 0) begin
						size_amplitude_V = size_amplitude_V - 1;
						while (size_amplitude_V == 0 && end_amplitude_V == 0) begin
							ap_c_n_tvin_trans_num_amplitude_V = ap_c_n_tvin_trans_num_amplitude_V + 1;
							read_token(fp_amplitude_V, token_amplitude_V); // should be [[transaction]] or [[[/runtime]]]
							if (token_amplitude_V == "[[transaction]]") begin
								read_token(fp_amplitude_V, token_amplitude_V); // should be transaction number
								read_token(fp_amplitude_V, token_amplitude_V); // should be size for hls::stream
								ret = $sscanf(token_amplitude_V, "%d", size_amplitude_V);
								read_token(fp_amplitude_V, token_amplitude_V); // should be [[/transaction]]
							end else if (token_amplitude_V == "[[[/runtime]]]") begin
								$fclose(fp_amplitude_V);
								end_amplitude_V = 1;
							end else begin
								$display("ERROR: unknown token_amplitude_V");
								$finish;
							end
						end
					end
				end
			end else begin
				ap_c_n_tvin_trans_num_amplitude_V = ap_c_n_tvin_trans_num_amplitude_V + 1;
			end
		end
	end
	

reg dump_tvout_finish_threshold_V;

initial begin : dump_tvout_runtime_sign_threshold_V
	integer fp;
	dump_tvout_finish_threshold_V = 0;
	fp = $fopen(`AUTOTB_TVOUT_threshold_V_out_wrapc, "w");
	if (fp == 0) begin
		$display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_threshold_V_out_wrapc);
		$display("ERROR: Simulation using HLS TB failed.");
		$finish;
	end
	$fdisplay(fp,"[[[runtime]]]");
	$fclose(fp);
	wait (done_cnt == `AUTOTB_TRANSACTION_NUM);
	// last transaction is saved at negedge right after last done
	@ (posedge AESL_clock);
	@ (posedge AESL_clock);
	@ (posedge AESL_clock);
	fp = $fopen(`AUTOTB_TVOUT_threshold_V_out_wrapc, "a");
	if (fp == 0) begin
		$display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_threshold_V_out_wrapc);
		$display("ERROR: Simulation using HLS TB failed.");
		$finish;
	end
	$fdisplay(fp,"[[[/runtime]]]");
	$fclose(fp);
	dump_tvout_finish_threshold_V = 1;
end

always @ (negedge AESL_clock) begin
    if(AESL_reset)
    begin
        AESL_clk_counter <= 0;
    end 
    else begin
        AESL_clk_counter = AESL_clk_counter + 1;
    end
end

always @ (posedge AESL_clock or posedge AESL_reset) begin
	if (AESL_reset) begin
		AESL_mLatCnterOut_addr = 0;
		AESL_mLatCnterOut[AESL_mLatCnterOut_addr] = AESL_clk_counter + 1;
	end else if (AESL_done && AESL_mLatCnterOut_addr < `AUTOTB_TRANSACTION_NUM + 1) begin
		AESL_mLatCnterOut[AESL_mLatCnterOut_addr] = AESL_clk_counter;
		AESL_mLatCnterOut_addr = AESL_mLatCnterOut_addr + 1;
	end
end

always @ (posedge AESL_clock or posedge AESL_reset) begin
	if (AESL_reset) begin
		reported_stuck_cnt <= 0;
	end else if (AESL_done && AESL_mLatCnterOut_addr < `AUTOTB_TRANSACTION_NUM + 1) begin
		reported_stuck <= 0;
	end else if (reported_stuck == 0 && reported_stuck_cnt < 4) begin
		if (AESL_mLatCnterIn_addr > AESL_mLatCnterOut_addr) begin
			if (AESL_clk_counter - AESL_mLatCnterIn[AESL_mLatCnterOut_addr] > 10000 && AESL_clk_counter - AESL_mLatCnterIn[AESL_mLatCnterOut_addr] > 10 * 1080043) begin
				$display("WARNING: The latency is much larger than expected. Simulation may stuck.");
				reported_stuck <= 1;
				reported_stuck_cnt <= reported_stuck_cnt + 1;
			end
		end
	end
end
always @ (posedge AESL_clock or posedge AESL_reset) begin
	if (AESL_reset) begin
		AESL_mLatCnterIn_addr = 0;
	end else begin
		if (AESL_start && AESL_mLatCnterIn_addr == 0) begin
			AESL_mLatCnterIn[AESL_mLatCnterIn_addr] = AESL_clk_counter;
			AESL_mLatCnterIn_addr = AESL_mLatCnterIn_addr + 1;
		end else if (AESL_ready && AESL_mLatCnterIn_addr < `AUTOTB_TRANSACTION_NUM + 1) begin
			AESL_mLatCnterIn[AESL_mLatCnterIn_addr] = AESL_clk_counter;
			AESL_mLatCnterIn_addr = AESL_mLatCnterIn_addr + 1;
		end
	end
end

initial begin : performance_check
	integer transaction_counter;
	integer i;
	integer fp;

	integer latthistime;
	integer lattotal;
	integer latmax;
	integer latmin;


	integer thrthistime;
	integer thrtotal;
	integer thrmax;
	integer thrmin;

	integer lataver;
	integer thraver;
	reg [31 : 0] lat_array [0 : `AUTOTB_TRANSACTION_NUM];
	reg [31 : 0] thr_array [0 : `AUTOTB_TRANSACTION_NUM];

	i = 0;
	lattotal = 0;
	latmax = 0;
	latmin = 32'h 7fffffff;
	lataver = 0;

	thrtotal = 0;
	thrmax = 0;
	thrmin = 32'h 7fffffff;
	thraver = 0;

	@(negedge AESL_clock);

	@(negedge AESL_reset);
	while (done_cnt < `AUTOTB_TRANSACTION_NUM) begin
		@(posedge AESL_clock);
	end

	#0.001

	for (i = 0; i < `AUTOTB_TRANSACTION_NUM; i = i + 1) begin
		latthistime = AESL_mLatCnterOut[i] - AESL_mLatCnterIn[i];
		lat_array[i] = latthistime;
		if (latthistime > latmax) latmax = latthistime;
		if (latthistime < latmin) latmin = latthistime;
		lattotal = lattotal + latthistime;
		if (`AUTOTB_TRANSACTION_NUM == 1) begin
			thrthistime = latthistime;
		end else begin
			thrthistime = AESL_mLatCnterIn[i + 1] - AESL_mLatCnterIn[i];
		end
		thr_array[i] = thrthistime;
		if (thrthistime > thrmax) thrmax = thrthistime;
		if (thrthistime < thrmin) thrmin = thrthistime;
		thrtotal = thrtotal + thrthistime;
	end

	lataver = lattotal / `AUTOTB_TRANSACTION_NUM;
	thraver = thrtotal / `AUTOTB_TRANSACTION_NUM;

	fp = $fopen(`AUTOTB_LAT_RESULT_FILE, "w");

	if (`AUTOTB_TRANSACTION_NUM == 1) begin
		thrmax  = 0;
		thrmin  = 0;
		thraver = 0;
		$fdisplay(fp, "$MAX_LATENCY = \"%0d\"", latmax);
		$fdisplay(fp, "$MIN_LATENCY = \"%0d\"", latmin);
		$fdisplay(fp, "$AVER_LATENCY = \"%0d\"", lataver);
		$fdisplay(fp, "$MAX_THROUGHPUT = \"%0d\"", thrmax);
		$fdisplay(fp, "$MIN_THROUGHPUT = \"%0d\"", thrmin);
		$fdisplay(fp, "$AVER_THROUGHPUT = \"%0d\"", thraver);
	end else begin
		// $::AESL_AUTOSIM::gDataflowTaskPipelineFlag && $::AESL_AUTOSIM::gnoPortSwitchingFlag == 0
		$fdisplay(fp, "$MAX_LATENCY = \"%0d\"", latmax );
		$fdisplay(fp, "$MIN_LATENCY = \"%0d\"", latmin );
		$fdisplay(fp, "$AVER_LATENCY = \"%0d\"", lataver );
		$fdisplay(fp, "$MAX_THROUGHPUT = \"%0d\"", thrmax );
		$fdisplay(fp, "$MIN_THROUGHPUT = \"%0d\"", thrmin );
		$fdisplay(fp, "$AVER_THROUGHPUT = \"%0d\"", thraver );
	end

	$fclose(fp);

	fp = $fopen(`AUTOTB_PER_RESULT_TRANS_FILE, "w");
	$fdisplay(fp, "%20s%16s%16s", "", "latency", "interval");
	if (`AUTOTB_TRANSACTION_NUM == 1) begin
		i = 0;
		thr_array[i] = 0;
		$fdisplay(fp, "transaction%8d:%16d%16d", i, lat_array[i], thr_array[i]);
	end else begin
		for (i = 0; i < AESL_mLatCnterOut_addr; i = i + 1) begin
			$fdisplay(fp, "transaction%8d:%16d%16d", i, lat_array[i], thr_array[i]);
		end
	end
	$fclose(fp);
end

endmodule
