// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="peaks,hls_ip_2015_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.100000,HLS_SYN_LAT=120013,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=304,HLS_SYN_LUT=800}" *)

module peaks (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        samples_V_dout,
        samples_V_empty_n,
        samples_V_read,
        amplitude_V_din,
        amplitude_V_full_n,
        amplitude_V_write,
        locations_V_din,
        locations_V_full_n,
        locations_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 5'b1;
parameter    ap_ST_st2_fsm_1 = 5'b10;
parameter    ap_ST_st3_fsm_2 = 5'b100;
parameter    ap_ST_pp0_stg0_fsm_3 = 5'b1000;
parameter    ap_ST_st11_fsm_4 = 5'b10000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv17_0 = 17'b00000000000000000;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv17_1D4C0 = 17'b11101010011000000;
parameter    ap_const_lv17_1 = 17'b1;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv23_0 = 23'b00000000000000000000000;
parameter    ap_const_lv5_4 = 5'b100;
parameter    ap_const_lv5_2 = 5'b10;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] samples_V_dout;
input   samples_V_empty_n;
output   samples_V_read;
output  [31:0] amplitude_V_din;
input   amplitude_V_full_n;
output   amplitude_V_write;
output  [31:0] locations_V_din;
input   locations_V_full_n;
output   locations_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg samples_V_read;
reg amplitude_V_write;
reg locations_V_write;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm = 5'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_21;
reg   [16:0] tmp_6_reg_111;
reg   [31:0] shift_buf_1_2_reg_122;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg   [0:0] exitcond_reg_362;
reg    ap_sig_bdd_52;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg   [0:0] or_cond_reg_409;
reg    ap_sig_bdd_72;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg   [31:0] shift_buf_1_9_reg_132;
reg   [31:0] ap_reg_ppstg_shift_buf_1_9_reg_132_pp0_it2;
reg   [31:0] ap_reg_ppstg_shift_buf_1_9_reg_132_pp0_it3;
reg   [31:0] ap_reg_ppstg_shift_buf_1_9_reg_132_pp0_it4;
reg   [31:0] ap_reg_ppstg_shift_buf_1_9_reg_132_pp0_it5;
wire   [1:0] indvarinc_fu_156_p2;
reg   [1:0] indvarinc_reg_343;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_92;
wire   [0:0] tmp_1_fu_172_p2;
reg   [0:0] tmp_1_reg_348;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_103;
wire   [0:0] exitcond_fu_184_p2;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_3;
reg    ap_sig_bdd_113;
reg   [0:0] ap_reg_ppstg_exitcond_reg_362_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond_reg_362_pp0_it2;
reg   [0:0] ap_reg_ppstg_exitcond_reg_362_pp0_it3;
reg   [0:0] ap_reg_ppstg_exitcond_reg_362_pp0_it4;
wire   [16:0] i_fu_190_p2;
wire   [31:0] tmp_18_fu_196_p1;
reg   [31:0] tmp_18_reg_371;
reg   [31:0] ap_reg_ppstg_tmp_18_reg_371_pp0_it1;
reg   [31:0] ap_reg_ppstg_tmp_18_reg_371_pp0_it2;
reg   [31:0] ap_reg_ppstg_tmp_18_reg_371_pp0_it3;
reg   [31:0] ap_reg_ppstg_tmp_18_reg_371_pp0_it4;
reg   [31:0] ap_reg_ppstg_tmp_18_reg_371_pp0_it5;
reg   [31:0] tmp_20_reg_376;
reg   [31:0] ap_reg_ppstg_tmp_20_reg_376_pp0_it2;
wire   [0:0] tmp_2_fu_230_p2;
reg   [0:0] tmp_2_reg_383;
reg   [0:0] ap_reg_ppstg_tmp_2_reg_383_pp0_it2;
reg   [0:0] ap_reg_ppstg_tmp_2_reg_383_pp0_it3;
wire   [0:0] tmp_7_fu_266_p2;
reg   [0:0] tmp_7_reg_388;
wire   [0:0] tmp_14_fu_301_p2;
reg   [0:0] tmp_14_reg_394;
wire   [0:0] tmp_11_fu_311_p2;
reg   [0:0] tmp_11_reg_399;
wire   [0:0] tmp_17_fu_321_p2;
reg   [0:0] tmp_17_reg_404;
wire   [0:0] or_cond_fu_327_p2;
wire   [1:0] invdar_phi_fu_104_p4;
reg   [1:0] invdar_reg_100;
reg   [31:0] shift_buf_1_2_phi_fu_125_p4;
reg   [31:0] shift_buf_1_9_phi_fu_137_p4;
wire   [31:0] shift_buf_fu_72;
wire   [31:0] shift_buf_1_fu_76;
wire   [31:0] shift_buf_1_2_to_int_fu_200_p1;
wire   [7:0] tmp_3_fu_204_p4;
wire   [22:0] tmp_4_fu_214_p1;
wire   [0:0] notrhs_fu_224_p2;
wire   [0:0] notlhs_fu_218_p2;
wire   [31:0] shift_buf_1_to_int_fu_236_p1;
wire   [7:0] tmp_8_fu_240_p4;
wire   [22:0] tmp_5_fu_250_p1;
wire   [0:0] notrhs5_fu_260_p2;
wire   [0:0] notlhs4_fu_254_p2;
wire   [31:0] shift_buf_0_to_int_fu_272_p1;
wire   [7:0] tmp_12_fu_275_p4;
wire   [22:0] tmp_13_fu_285_p1;
wire   [0:0] notrhs9_fu_295_p2;
wire   [0:0] notlhs8_fu_289_p2;
wire   [0:0] tmp_9_fu_307_p2;
wire   [0:0] grp_fu_144_p2;
wire   [0:0] tmp_15_fu_317_p2;
wire   [0:0] grp_fu_150_p2;
reg    grp_fu_144_ce;
wire   [4:0] grp_fu_144_opcode;
reg    grp_fu_150_ce;
wire   [4:0] grp_fu_150_opcode;
reg    ap_sig_cseq_ST_st11_fsm_4;
reg    ap_sig_bdd_334;
reg   [4:0] ap_NS_fsm;


peaks_fcmp_32ns_32ns_1_4 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
peaks_fcmp_32ns_32ns_1_4_U0(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( shift_buf_1_2_phi_fu_125_p4 ),
    .din1( shift_buf_1_9_phi_fu_137_p4 ),
    .ce( grp_fu_144_ce ),
    .opcode( grp_fu_144_opcode ),
    .dout( grp_fu_144_p2 )
);

peaks_fcmp_32ns_32ns_1_4 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
peaks_fcmp_32ns_32ns_1_4_U1(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( shift_buf_1_9_phi_fu_137_p4 ),
    .din1( samples_V_dout ),
    .ce( grp_fu_150_ce ),
    .opcode( grp_fu_150_opcode ),
    .dout( grp_fu_150_p2 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if ((~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(ap_const_lv1_0 == exitcond_fu_184_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(ap_const_lv1_0 == tmp_1_reg_348))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if ((~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(ap_const_lv1_0 == tmp_1_reg_348))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
            if (~(ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) begin
                ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
            end else if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) begin
                ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
            end
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(ap_const_lv1_0 == tmp_1_reg_348))) begin
            ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == tmp_1_reg_348))) begin
        invdar_reg_100 <= indvarinc_reg_343;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        invdar_reg_100 <= ap_const_lv2_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(ap_const_lv1_0 == tmp_1_reg_348))) begin
        shift_buf_1_2_reg_122 <= shift_buf_1_fu_76;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_362_pp0_it1))) begin
        shift_buf_1_2_reg_122 <= shift_buf_1_9_reg_132;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(ap_const_lv1_0 == tmp_1_reg_348))) begin
        shift_buf_1_9_reg_132 <= shift_buf_fu_72;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_362_pp0_it1))) begin
        shift_buf_1_9_reg_132 <= tmp_20_reg_376;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(ap_const_lv1_0 == tmp_1_reg_348))) begin
        tmp_6_reg_111 <= ap_const_lv17_0;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_lv1_0 == exitcond_fu_184_p2))) begin
        tmp_6_reg_111 <= i_fu_190_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3))) begin
        ap_reg_ppstg_exitcond_reg_362_pp0_it1 <= exitcond_reg_362;
        ap_reg_ppstg_tmp_18_reg_371_pp0_it1[16 : 0] <= tmp_18_reg_371[16 : 0];
        exitcond_reg_362 <= exitcond_fu_184_p2;
    end
end

always @ (posedge ap_clk) begin
    if (~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
        ap_reg_ppstg_exitcond_reg_362_pp0_it2 <= ap_reg_ppstg_exitcond_reg_362_pp0_it1;
        ap_reg_ppstg_exitcond_reg_362_pp0_it3 <= ap_reg_ppstg_exitcond_reg_362_pp0_it2;
        ap_reg_ppstg_exitcond_reg_362_pp0_it4 <= ap_reg_ppstg_exitcond_reg_362_pp0_it3;
        ap_reg_ppstg_shift_buf_1_9_reg_132_pp0_it2 <= shift_buf_1_9_reg_132;
        ap_reg_ppstg_shift_buf_1_9_reg_132_pp0_it3 <= ap_reg_ppstg_shift_buf_1_9_reg_132_pp0_it2;
        ap_reg_ppstg_shift_buf_1_9_reg_132_pp0_it4 <= ap_reg_ppstg_shift_buf_1_9_reg_132_pp0_it3;
        ap_reg_ppstg_shift_buf_1_9_reg_132_pp0_it5 <= ap_reg_ppstg_shift_buf_1_9_reg_132_pp0_it4;
        ap_reg_ppstg_tmp_18_reg_371_pp0_it2[16 : 0] <= ap_reg_ppstg_tmp_18_reg_371_pp0_it1[16 : 0];
        ap_reg_ppstg_tmp_18_reg_371_pp0_it3[16 : 0] <= ap_reg_ppstg_tmp_18_reg_371_pp0_it2[16 : 0];
        ap_reg_ppstg_tmp_18_reg_371_pp0_it4[16 : 0] <= ap_reg_ppstg_tmp_18_reg_371_pp0_it3[16 : 0];
        ap_reg_ppstg_tmp_18_reg_371_pp0_it5[16 : 0] <= ap_reg_ppstg_tmp_18_reg_371_pp0_it4[16 : 0];
        ap_reg_ppstg_tmp_20_reg_376_pp0_it2 <= tmp_20_reg_376;
        ap_reg_ppstg_tmp_2_reg_383_pp0_it2 <= tmp_2_reg_383;
        ap_reg_ppstg_tmp_2_reg_383_pp0_it3 <= ap_reg_ppstg_tmp_2_reg_383_pp0_it2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        indvarinc_reg_343 <= indvarinc_fu_156_p2;
        tmp_1_reg_348 <= tmp_1_fu_172_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_362_pp0_it4))) begin
        or_cond_reg_409 <= or_cond_fu_327_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_362_pp0_it3))) begin
        tmp_11_reg_399 <= tmp_11_fu_311_p2;
        tmp_17_reg_404 <= tmp_17_fu_321_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_362_pp0_it2))) begin
        tmp_14_reg_394 <= tmp_14_fu_301_p2;
        tmp_7_reg_388 <= tmp_7_fu_266_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_lv1_0 == exitcond_fu_184_p2))) begin
        tmp_18_reg_371[16 : 0] <= tmp_18_fu_196_p1[16 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_362 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3))) begin
        tmp_20_reg_376 <= samples_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_362 == ap_const_lv1_0) & ~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3))) begin
        tmp_2_reg_383 <= tmp_2_fu_230_p2;
    end
end

always @ (ap_sig_bdd_52 or ap_reg_ppiten_pp0_it1 or or_cond_reg_409 or ap_sig_bdd_72 or ap_reg_ppiten_pp0_it6) begin
    if ((~(ap_const_lv1_0 == or_cond_reg_409) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        amplitude_V_write = ap_const_logic_1;
    end else begin
        amplitude_V_write = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st11_fsm_4) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_4)) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st11_fsm_4) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_4)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_113) begin
    if (ap_sig_bdd_113) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_334) begin
    if (ap_sig_bdd_334) begin
        ap_sig_cseq_ST_st11_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st11_fsm_4 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_21) begin
    if (ap_sig_bdd_21) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_92) begin
    if (ap_sig_bdd_92) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_103) begin
    if (ap_sig_bdd_103) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_52 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_72 or ap_reg_ppiten_pp0_it6 or ap_sig_cseq_ST_pp0_stg0_fsm_3) begin
    if ((~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3))) begin
        grp_fu_144_ce = ap_const_logic_1;
    end else begin
        grp_fu_144_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_52 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_72 or ap_reg_ppiten_pp0_it6 or ap_sig_cseq_ST_pp0_stg0_fsm_3) begin
    if ((~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3))) begin
        grp_fu_150_ce = ap_const_logic_1;
    end else begin
        grp_fu_150_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_52 or ap_reg_ppiten_pp0_it1 or or_cond_reg_409 or ap_sig_bdd_72 or ap_reg_ppiten_pp0_it6) begin
    if ((~(ap_const_lv1_0 == or_cond_reg_409) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))))) begin
        locations_V_write = ap_const_logic_1;
    end else begin
        locations_V_write = ap_const_logic_0;
    end
end

always @ (exitcond_reg_362 or ap_sig_bdd_52 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_72 or ap_reg_ppiten_pp0_it6 or ap_sig_cseq_ST_pp0_stg0_fsm_3) begin
    if (((exitcond_reg_362 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3))) begin
        samples_V_read = ap_const_logic_1;
    end else begin
        samples_V_read = ap_const_logic_0;
    end
end

always @ (shift_buf_1_2_reg_122 or ap_reg_ppiten_pp0_it2 or shift_buf_1_9_reg_132 or ap_reg_ppstg_exitcond_reg_362_pp0_it1) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_362_pp0_it1))) begin
        shift_buf_1_2_phi_fu_125_p4 = shift_buf_1_9_reg_132;
    end else begin
        shift_buf_1_2_phi_fu_125_p4 = shift_buf_1_2_reg_122;
    end
end

always @ (ap_reg_ppiten_pp0_it2 or shift_buf_1_9_reg_132 or ap_reg_ppstg_exitcond_reg_362_pp0_it1 or tmp_20_reg_376) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_362_pp0_it1))) begin
        shift_buf_1_9_phi_fu_137_p4 = tmp_20_reg_376;
    end else begin
        shift_buf_1_9_phi_fu_137_p4 = shift_buf_1_9_reg_132;
    end
end
always @ (ap_start or ap_CS_fsm or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_52 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_reg_ppiten_pp0_it5 or ap_sig_bdd_72 or ap_reg_ppiten_pp0_it6 or tmp_1_reg_348 or ap_sig_cseq_ST_pp0_stg0_fsm_3) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        ap_ST_st3_fsm_2 : 
        begin
            if (~(ap_const_lv1_0 == tmp_1_reg_348)) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_pp0_stg0_fsm_3 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it5)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_52 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6))) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2)))) begin
                ap_NS_fsm = ap_ST_st11_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end
        end
        ap_ST_st11_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


assign amplitude_V_din = ap_reg_ppstg_shift_buf_1_9_reg_132_pp0_it5;


always @ (ap_CS_fsm) begin
    ap_sig_bdd_103 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_113 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_21 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_334 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end


always @ (samples_V_empty_n or exitcond_reg_362) begin
    ap_sig_bdd_52 = ((samples_V_empty_n == ap_const_logic_0) & (exitcond_reg_362 == ap_const_lv1_0));
end


always @ (amplitude_V_full_n or locations_V_full_n or or_cond_reg_409) begin
    ap_sig_bdd_72 = (((locations_V_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == or_cond_reg_409)) | (~(ap_const_lv1_0 == or_cond_reg_409) & (amplitude_V_full_n == ap_const_logic_0)));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_92 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

assign exitcond_fu_184_p2 = (tmp_6_reg_111 == ap_const_lv17_1D4C0? 1'b1: 1'b0);

assign grp_fu_144_opcode = ap_const_lv5_4;

assign grp_fu_150_opcode = ap_const_lv5_2;

assign i_fu_190_p2 = (tmp_6_reg_111 + ap_const_lv17_1);

assign indvarinc_fu_156_p2 = (invdar_reg_100 + ap_const_lv2_1);

assign invdar_phi_fu_104_p4 = invdar_reg_100;

assign locations_V_din = ap_reg_ppstg_tmp_18_reg_371_pp0_it5;

assign notlhs4_fu_254_p2 = (tmp_8_fu_240_p4 != ap_const_lv8_FF? 1'b1: 1'b0);

assign notlhs8_fu_289_p2 = (tmp_12_fu_275_p4 != ap_const_lv8_FF? 1'b1: 1'b0);

assign notlhs_fu_218_p2 = (tmp_3_fu_204_p4 != ap_const_lv8_FF? 1'b1: 1'b0);

assign notrhs5_fu_260_p2 = (tmp_5_fu_250_p1 == ap_const_lv23_0? 1'b1: 1'b0);

assign notrhs9_fu_295_p2 = (tmp_13_fu_285_p1 == ap_const_lv23_0? 1'b1: 1'b0);

assign notrhs_fu_224_p2 = (tmp_4_fu_214_p1 == ap_const_lv23_0? 1'b1: 1'b0);

assign or_cond_fu_327_p2 = (tmp_11_reg_399 & tmp_17_reg_404);

assign shift_buf_0_to_int_fu_272_p1 = ap_reg_ppstg_tmp_20_reg_376_pp0_it2;

assign shift_buf_1_2_to_int_fu_200_p1 = shift_buf_1_2_phi_fu_125_p4;

assign shift_buf_1_fu_76 = ap_const_lv32_0;

assign shift_buf_1_to_int_fu_236_p1 = ap_reg_ppstg_shift_buf_1_9_reg_132_pp0_it2;

assign shift_buf_fu_72 = ap_const_lv32_0;

assign tmp_11_fu_311_p2 = (tmp_9_fu_307_p2 & grp_fu_144_p2);

assign tmp_12_fu_275_p4 = {{shift_buf_0_to_int_fu_272_p1[ap_const_lv32_1E : ap_const_lv32_17]}};

assign tmp_13_fu_285_p1 = shift_buf_0_to_int_fu_272_p1[22:0];

assign tmp_14_fu_301_p2 = (notrhs9_fu_295_p2 | notlhs8_fu_289_p2);

assign tmp_15_fu_317_p2 = (tmp_7_reg_388 & tmp_14_reg_394);

assign tmp_17_fu_321_p2 = (tmp_15_fu_317_p2 & grp_fu_150_p2);

assign tmp_18_fu_196_p1 = tmp_6_reg_111;

assign tmp_1_fu_172_p2 = (invdar_reg_100 == ap_const_lv2_2? 1'b1: 1'b0);

assign tmp_2_fu_230_p2 = (notrhs_fu_224_p2 | notlhs_fu_218_p2);

assign tmp_3_fu_204_p4 = {{shift_buf_1_2_to_int_fu_200_p1[ap_const_lv32_1E : ap_const_lv32_17]}};

assign tmp_4_fu_214_p1 = shift_buf_1_2_to_int_fu_200_p1[22:0];

assign tmp_5_fu_250_p1 = shift_buf_1_to_int_fu_236_p1[22:0];

assign tmp_7_fu_266_p2 = (notrhs5_fu_260_p2 | notlhs4_fu_254_p2);

assign tmp_8_fu_240_p4 = {{shift_buf_1_to_int_fu_236_p1[ap_const_lv32_1E : ap_const_lv32_17]}};

assign tmp_9_fu_307_p2 = (ap_reg_ppstg_tmp_2_reg_383_pp0_it3 & tmp_7_reg_388);
always @ (posedge ap_clk) begin
    tmp_18_reg_371[31:17] <= 15'b000000000000000;
    ap_reg_ppstg_tmp_18_reg_371_pp0_it1[31:17] <= 15'b000000000000000;
    ap_reg_ppstg_tmp_18_reg_371_pp0_it2[31:17] <= 15'b000000000000000;
    ap_reg_ppstg_tmp_18_reg_371_pp0_it3[31:17] <= 15'b000000000000000;
    ap_reg_ppstg_tmp_18_reg_371_pp0_it4[31:17] <= 15'b000000000000000;
    ap_reg_ppstg_tmp_18_reg_371_pp0_it5[31:17] <= 15'b000000000000000;
end



endmodule //peaks

